apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30001 # O cualquier puerto disponible en el rango 30000-32767
  type: NodePort
