apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: oscarhenriquezg/ms-eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-server.default.svc.cluster.local"
            - name: EUREKA_CLIENT_REGISTER-WITH-EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH-REGISTRY
              value: "false"
