apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: oscarhenriquezg/ms-eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "eureka-server.default.svc.cluster.local"
            - name: EUREKA_CLIENT_REGISTER-WITH-EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH-REGISTRY
              value: "false"
#            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
#              value: "true"
#            - name: SPRING_PROFILES_ACTIVE
#              value: "default"

#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8761
#            initialDelaySeconds: 10
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8761
#            initialDelaySeconds: 30
#            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      nodePort: 30001 # O cualquier puerto disponible en el rango 30000-32767
  type: NodePort
