apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-api-gtw
  labels:
    app: ms-api-gtw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-api-gtw
  template:
    metadata:
      labels:
        app: ms-api-gtw
    spec:
      containers:
        - name: ms-api-gtw
          image: oscarhenriquezg/ms-api-gtw:latest
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 10
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 30
#            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: ms-api-gtw
  labels:
    app: ms-api-gtw
spec:
  selector:
    app: ms-api-gtw
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
