apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-calculo-planilla-sueldos
  labels:
    app: ms-calculo-planilla-sueldos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-calculo-planilla-sueldos
  template:
    metadata:
      labels:
        app: ms-calculo-planilla-sueldos
    spec:
      containers:
        - name: ms-calculo-planilla-sueldos
          image: oscarhenriquezg/ms-calculo-planilla-sueldos:latest
          ports:
            - containerPort: 8083
          env:
            # Variables para Eureka
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            # Variables para Config Server
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            # Opcional: Perfil activo
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
            # Variables para la Base de Datos
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/bd_calculo_planilla_sueldos"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "mysecretpassword"
#          # Opcional: readiness/liveness checks
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8083
#            initialDelaySeconds: 10
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8083
#            initialDelaySeconds: 30
#            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: ms-calculo-planilla-sueldos
  labels:
    app: ms-calculo-planilla-sueldos
spec:
  selector:
    app: ms-calculo-planilla-sueldos
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
