apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-justificativos
  labels:
    app: ms-justificativos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-justificativos
  template:
    metadata:
      labels:
        app: ms-justificativos
    spec:
      containers:
        - name: ms-justificativos
          image: oscarhenriquezg/ms-justificativos:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/bd_justificativos"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "mysecretpassword"
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8081
#            initialDelaySeconds: 10
#            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8081
#            initialDelaySeconds: 30
#            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: ms-justificativos
  labels:
    app: ms-justificativos
spec:
  selector:
    app: ms-justificativos
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
